# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaNorm <- function(n) {
    .Call('PCspatreg_armaNorm', PACKAGE = 'PCspatreg', n)
}

GCN <- function(V, v) {
    .Call('PCspatreg_GCN', PACKAGE = 'PCspatreg', V, v)
}

GCN2 <- function(V, v) {
    .Call('PCspatreg_GCN2', PACKAGE = 'PCspatreg', V, v)
}

PCspatregMCMC <- function(y, X, K, sampleIndex, betaMean, betaSig, phiScale, burn, iter) {
    .Call('PCspatreg_PCspatregMCMC', PACKAGE = 'PCspatreg', y, X, K, sampleIndex, betaMean, betaSig, phiScale, burn, iter)
}

