// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// armaNorm
arma::vec armaNorm(int n);
RcppExport SEXP PCspatreg_armaNorm(SEXP nSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        arma::vec __result = armaNorm(n);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// GCN
arma::vec GCN(const arma::mat& V, const arma::vec& v);
RcppExport SEXP PCspatreg_GCN(SEXP VSEXP, SEXP vSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP );
        Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP );
        arma::vec __result = GCN(V, v);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// GCN2
arma::vec GCN2(const arma::mat& V, const arma::vec& v);
RcppExport SEXP PCspatreg_GCN2(SEXP VSEXP, SEXP vSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP );
        Rcpp::traits::input_parameter< const arma::vec& >::type v(vSEXP );
        arma::vec __result = GCN2(V, v);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// PCspatregMCMC
List PCspatregMCMC(const arma::vec& y, const arma::mat& X, const arma::mat& K, const arma::uvec& sampleIndex, const arma::vec& betaMean, const arma::mat& betaSig, const double& phiScale, const int& burn, const int& iter);
RcppExport SEXP PCspatreg_PCspatregMCMC(SEXP ySEXP, SEXP XSEXP, SEXP KSEXP, SEXP sampleIndexSEXP, SEXP betaMeanSEXP, SEXP betaSigSEXP, SEXP phiScaleSEXP, SEXP burnSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type K(KSEXP );
        Rcpp::traits::input_parameter< const arma::uvec& >::type sampleIndex(sampleIndexSEXP );
        Rcpp::traits::input_parameter< const arma::vec& >::type betaMean(betaMeanSEXP );
        Rcpp::traits::input_parameter< const arma::mat& >::type betaSig(betaSigSEXP );
        Rcpp::traits::input_parameter< const double& >::type phiScale(phiScaleSEXP );
        Rcpp::traits::input_parameter< const int& >::type burn(burnSEXP );
        Rcpp::traits::input_parameter< const int& >::type iter(iterSEXP );
        List __result = PCspatregMCMC(y, X, K, sampleIndex, betaMean, betaSig, phiScale, burn, iter);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
